Add code for creating a dataset using path on datastore
Azure/azureml-cheatsheets pull request #73
Opened 2021-06-11 22:15 UTC by fuhuifang

# PR into Azure/azureml-cheatsheets

## Checklist

I have:

- [ X] read and followed the [contributing guidelines](https://azure.github.io/azureml-cheatsheets/docs/misc/contributing)

## Changes

- Add a code example for creating a Dataset given a relative path on datastore
- Add a placeholder for creating a Dataset from local files

2021-06-11 22:16 UTC, fuhuifang commented
From https://docs.microsoft.com/en-us/azure/machine-learning/how-to-create-register-datasets:

Upload files from a local directory and create a FileDataset in a single method with the public preview method, upload_directory(). This method is an experimental preview feature, and may change at any time.

2021-06-17 23:22 UTC, aminsaied requested changes

2021-06-17 23:22 UTC, aminsaied commented on website/docs/cheatsheets/python/v1/data.md
> +dataset_name = os.environ.get('ADL_DATA_SET', 'folder_data')
Nit: For the sake of simplicity, can we avoid reading from env vars and just set name = "<dataset_name>" or something generic?

2021-06-17 23:22 UTC, aminsaied commented on website/docs/cheatsheets/python/v1/data.md
> +folder_data = Dataset.File.from_files(path=(datastore, os.environ.get('ADL_DATA_RELATIVE_PATH', 'local/test/')))
As above, let's just use a generic sounding path here

2021-06-17 23:22 UTC, aminsaied commented on website/docs/cheatsheets/python/v1/data.md
> +    destination=(datastore, "test_path/{run-id}"),
Same again, lets use a generic path. Note: the { } assume you are using an f string f"", which this example doesn't. I'd suggest

destination=(datastore, "path/to/output")

2021-06-17 23:22 UTC, aminsaied commented on website/docs/cheatsheets/python/v1/data.md
> +        command=["python", "run.py", "--output_dir", output_data.as_mount()],
Nit: I think command is less well known than script and arguments, I'd suggest doing

...
script="run.py",
arguments=["--output_dir", output_data.as_mount()],
...

2021-06-24 23:10 UTC, aminsaied approved these changes

2021-06-24 23:10 UTC, merged